// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBGxO9RIGYM7UC9xNr2o3WQt5qpHDB8prM',
    appId: '1:114806408792:web:acd0934508bcd3ed05ac2d',
    messagingSenderId: '114806408792',
    projectId: 'medquiz-74114',
    authDomain: 'medquiz-74114.firebaseapp.com',
    storageBucket: 'medquiz-74114.firebasestorage.app',
    measurementId: 'G-1NW9FWSF9E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBsYK0tdO3uTXi5q8z18uIBYs6N1AepiXY',
    appId: '1:114806408792:android:686da38fc79a386205ac2d',
    messagingSenderId: '114806408792',
    projectId: 'medquiz-74114',
    storageBucket: 'medquiz-74114.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCm-NYyoVss3H6k7_kMjcZOQaxEHG3zxNY',
    appId: '1:114806408792:ios:24fef42107fd2e3505ac2d',
    messagingSenderId: '114806408792',
    projectId: 'medquiz-74114',
    storageBucket: 'medquiz-74114.firebasestorage.app',
    iosBundleId: 'com.example.myapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCm-NYyoVss3H6k7_kMjcZOQaxEHG3zxNY',
    appId: '1:114806408792:ios:24fef42107fd2e3505ac2d',
    messagingSenderId: '114806408792',
    projectId: 'medquiz-74114',
    storageBucket: 'medquiz-74114.firebasestorage.app',
    iosBundleId: 'com.example.myapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBGxO9RIGYM7UC9xNr2o3WQt5qpHDB8prM',
    appId: '1:114806408792:web:ac6b2ed0154b43e805ac2d',
    messagingSenderId: '114806408792',
    projectId: 'medquiz-74114',
    authDomain: 'medquiz-74114.firebaseapp.com',
    storageBucket: 'medquiz-74114.firebasestorage.app',
    measurementId: 'G-ERPP2EDMXL',
  );
}
